import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Theme = 'editorial' | 'workbench' | 'graph' | 'quiet';
type Lang = 'en' | 'zh';
const themes: Theme[] = ['editorial', 'workbench', 'graph', 'quiet'];
const copy = {
  en: {
    nav: ['Features', 'Scenes', 'FAQ'], gallery: 'Prototype gallery', language: '中文',
    eyebrow: 'Local-first knowledge, thoughtfully connected', title: 'Your knowledge should stay yours.',
    sub: 'NexNote brings block editing, wikilinks, Git history, and an explicit native AI layer into one calm desktop app.',
    features: 'One knowledge base. Four ways to see it.', scenes: 'Product scenes', placeholder: 'Internal prototype panel · not a real screenshot',
    download: 'Download latest', github: 'View on GitHub', faq: 'Questions, answered.', footer: 'A local-first knowledge base for people who think in links.',
    open: 'Open prototype', back: 'Back to gallery', directions: { editorial: 'Editorial Knowledge', workbench: 'Local-first Workbench', graph: 'Graph Intelligence', quiet: 'Quiet Precision' },
    descriptions: { editorial: 'A considered reading room for ideas, references, and long-form thinking.', workbench: 'A dependable instrument for pages, commits, and deliberate AI actions.', graph: 'See the relationships behind your knowledge, then follow the next useful edge.', quiet: 'A focused, precise surface that lets the work—not the interface—lead.' },
    facts: [['Block editor', 'Drag, nest, and shape paragraphs, lists, code, tables, and media. Export standard Markdown.'], ['Wikilinks & backlinks', 'Link pages with [[Page|alias]], inspect linked mentions, and rename safely across the vault.'], ['Git under the hood', 'Automatic snapshots stay distinct from manual commits, with a per-page version timeline.'], ['Native AI layer', 'Bring an OpenAI-compatible provider. Explicit intent, streaming answers, cited sources, and permission modes.'], ['Progressive recall', 'Keyword, tag, and metadata filtering expands through wikilinks before vector reranking.'], ['Local-first format', 'Plain Markdown in a folder you own, a rebuildable relation index, no account, cloud, or telemetry.']],
    faqs: [['Does NexNote need an account?', 'No. Your pages and settings stay local. Internet is only needed for a cloud AI provider, Git remotes, or updates.'], ['What is a vault?', 'A normal folder of Markdown files with a .nexnote/ index directory and Git history.'], ['Can I import an Obsidian vault?', 'Yes. Wikilinks, aliases, tags, callouts, frontmatter, and block anchors are supported.'], ['Is my data safe?', 'Uninstalling the app does not remove your vault. The relation index can be rebuilt from your files.'], ['How does Git history work?', 'Automatic snapshots are clearly separated from manual commits; you can inspect a timeline, restore a version, or disable autosave.'], ['Where can I download NexNote?', 'The latest builds are on GitHub Releases for macOS Apple Silicon/Intel, Windows x64, and Linux x64. If macOS blocks first launch, use right-click → Open or Privacy & Security → Open Anyway.']],
  },
  zh: {
    nav: ['功能', '实景', 'FAQ'], gallery: '原型画廊', language: 'English',
    eyebrow: '本地优先的知识，安静地彼此连接', title: '你的知识，应该始终属于你。',
    sub: 'NexNote 将块编辑、双链、Git 历史与显式原生 AI 层，放进一个从容的桌面应用。',
    features: '一个知识库，四种观看方式。', scenes: '产品实景', placeholder: '内部原型面板 · 非真实截图',
    download: '下载最新版本', github: '在 GitHub 查看', faq: '常见问题，一次回答。', footer: '为用链接思考的人打造的本地优先知识库。',
    open: '打开原型', back: '返回画廊', directions: { editorial: 'Editorial Knowledge', workbench: 'Local-first Workbench', graph: 'Graph Intelligence', quiet: 'Quiet Precision' },
    descriptions: { editorial: '为想法、参考与长篇思考准备的阅读室。', workbench: '管理页面、提交与审慎 AI 操作的可靠工具。', graph: '看见知识背后的关系，沿着下一条有用的边继续探索。', quiet: '专注、精准的界面，让工作而不是界面成为主角。' },
    facts: [['块编辑', '拖拽、嵌套并组织段落、列表、代码、表格与媒体，导出标准 Markdown。'], ['双链与反向链接', '使用 [[页面|别名]] 链接页面，查看引用，并安全地批量重命名。'], ['Git 版本底座', '自动快照与手动提交清晰区分，每个页面都有版本时间线。'], ['原生 AI 层', '接入兼容 OpenAI 的供应商。显式意图、流式结果、参考来源与权限模式。'], ['渐进式召回', '先按关键词、标签、元数据筛选，再扩展双链，最后进行向量重排。'], ['本地优先格式', 'Markdown 文件归你所有，关系索引可重建；不需要账号、云同步或追踪。']],
    faqs: [['NexNote 需要账号吗？', '不需要。页面与设置保存在本地。只有使用云端 AI、Git 远程或检查更新时需要联网。'], ['什么是 vault？', '普通文件夹，包含 Markdown 文件、.nexnote/ 索引目录与 Git 历史。'], ['能导入 Obsidian vault 吗？', '可以，支持双链、别名、标签、Callout、Frontmatter 与块锚点。'], ['数据安全吗？', '卸载应用不会删除 vault，关系索引也可以从文件重新构建。'], ['Git 历史如何工作？', '自动快照与手动提交清晰分开，可查看时间线、恢复版本或关闭自动提交。'], ['从哪里下载？', '最新版本在 GitHub Releases，支持 macOS Apple Silicon/Intel、Windows x64 与 Linux x64。若 macOS 阻止首次打开，可右键选择“打开”，或在隐私与安全中允许。']],
  },
} as const;

type Text = (typeof copy)[Lang];
function pathFor(lang: Lang, theme?: Theme) { return theme ? `${lang === 'zh' ? '/zh' : ''}/proto/${theme}` : lang === 'zh' ? '/zh' : '/'; }
function currentRoute(): { lang: Lang; theme?: Theme } { const parts = location.pathname.split('/').filter(Boolean); const lang: Lang = parts[0] === 'zh' ? 'zh' : 'en'; const candidate = (lang === 'zh' ? parts[2] : parts[1]) as Theme | undefined; return { lang, theme: candidate && themes.includes(candidate) ? candidate : undefined }; }
function Link({ href, children, className = '' }: { href: string; children: React.ReactNode; className?: string }) { return <a className={className} href={href}>{children}</a>; }
function Mark() { return <img className="mark" src="/brand/mark.svg" alt="NexNote" />; }
function Chrome({ lang, text, children, gallery = false }: { lang: Lang; text: Text; children: React.ReactNode; gallery?: boolean }) { return <><header className="site-header"><Link href={pathFor(lang)} className="brand"><Mark /><span>NexNote</span></Link><nav>{text.nav.map((item, i) => <Link key={item} href={gallery ? `#${['features','scenes','faq'][i]}` : `#${['features','scenes','faq'][i]}`}>{item}</Link>)}</nav><div className="header-actions"><Link href={lang === 'zh' ? '/' : '/zh'} className="language">{text.language}</Link><Link href="https://github.com/Aiden-FE/nexnote" className="github">GitHub</Link></div></header>{children}</>; }
function Mock({ kind, text }: { kind: string; text: Text }) { return <div className={`mock mock-${kind}`}><div className="mock-top"><span className="dots">● ● ●</span><span>NexNote / Demo Vault</span><span>⌘K</span></div><div className="mock-body">{kind === 'editor' && <><aside><b>Pages</b><span>◈ Home</span><span>◈ Research</span><span>◈ Ideas</span></aside><main><small>PAGE · RESEARCH</small><h3>Patterns that compound</h3><p className="line wide" /><p className="line" /><p className="line medium" /><div className="tag">[[Progressive Recall]]</div></main><aside className="mentions"><b>Linked mentions</b><span>3 references</span><span>confidence 0.86</span></aside></>}{kind === 'graph' && <div className="graph-art"><i/><i/><i/><i/><i/><b/><b/><b/><strong>Relation Index</strong></div>}{kind === 'chat' && <><main><small>CONTEXT INJECTION</small><h3>Ask your knowledge</h3><p className="line wide" /><p className="line medium" /></main><aside className="chat"><b>AI session</b><span>3 cited sources</span><p>Progressive recall found 8 related pages.</p><button>Accept edit proposal</button></aside></>}</div><div className="placeholder-label">{text.placeholder}</div></div> }
function Faq({ text }: { text: Text }) { return <section id="faq" className="faq section"><p className="eyebrow">FAQ</p><h2>{text.faq}</h2><div className="faq-grid">{text.faqs.map(([q, a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>; }
function Cta({ text, lang }: { text: Text; lang: Lang }) { return <section className="cta section"><div><p className="eyebrow">NEXNOTE · v0.0.11</p><h2>{lang === 'zh' ? '把知识带回本地。' : 'Bring your knowledge home.'}</h2></div><div className="cta-actions"><Link href="https://github.com/Aiden-FE/nexnote/releases/latest" className="button primary">{text.download} ↗</Link><Link href="https://github.com/Aiden-FE/nexnote" className="button secondary">{text.github}</Link></div></section>; }
function Footer({ text, lang }: { text: Text; lang: Lang }) { return <footer><div className="brand footer-brand"><Mark /><span>NexNote</span></div><p>{text.footer}</p><span>© 2026 NexNote contributors</span><Link href={pathFor(lang)}>{text.gallery}</Link></footer>; }
function Gallery({ lang, text }: { lang: Lang; text: Text }) { const [mobile, setMobile] = useState(false); return <Chrome lang={lang} text={text} gallery><main className="gallery section"><div className="gallery-intro"><p className="eyebrow">NEXNOTE / PROTOTYPE GALLERY</p><h1>{lang === 'zh' ? '一个产品，四种方向。' : 'One product, four directions.'}</h1><p>{lang === 'zh' ? '探索四个整案原型。共享同一套产品事实，仅视觉与叙事不同。' : 'Explore four full-stack prototypes. The product facts stay constant; the visual language changes.'}</p><div className="preview-toggle"><button className={!mobile ? 'active' : ''} onClick={() => setMobile(false)}>Desktop</button><button className={mobile ? 'active' : ''} onClick={() => setMobile(true)}>Mobile</button></div></div><div className={`gallery-grid ${mobile ? 'mobile-previews' : ''}`}>{themes.map((theme, i) => <article className={`gallery-card card-${theme}`} key={theme}><div className="mini-preview"><div className="mini-bar"/><div className="mini-copy"><b>∕∕ {String(i + 1).padStart(2, '0')}</b><strong>{text.directions[theme]}</strong><span>{text.sub}</span></div><div className="mini-lines"/></div><div className="card-body"><p className="card-index">0{i + 1} / 04</p><h2>{text.directions[theme]}</h2><p>{text.descriptions[theme]}</p><Link className="text-link" href={pathFor(lang, theme)}>{text.open} <span>↗</span></Link></div></article>)}</div></main><Footer text={text} lang={lang} /></Chrome>; }
function Prototype({ lang, text, theme }: { lang: Lang; text: Text; theme: Theme }) { const accent = { editorial: 'Read deeply. Link widely.', workbench: 'A workbench for thinking in public and private.', graph: 'Every page is an edge waiting to be followed.', quiet: 'Less interface. More signal.' }[theme]; return <Chrome lang={lang} text={text}><main className={`prototype theme-${theme}`}><section className="hero section"><div className="hero-copy"><Link className="back-link" href={pathFor(lang)}>← {text.back}</Link><p className="eyebrow">{text.directions[theme]}</p><h1>{lang === 'zh' ? ({ editorial: '让想法像文章一样生长。', workbench: '知识，是一件可依赖的工具。', graph: '看见知识之间的下一条边。', quiet: '清晰，是一种生产力。' }[theme]) : accent}</h1><p>{text.descriptions[theme]} {text.sub}</p><div className="hero-actions"><Link href="https://github.com/Aiden-FE/nexnote/releases/latest" className="button primary">{text.download} ↗</Link><Link href="#features" className="button ghost">{lang === 'zh' ? '探索功能' : 'Explore features'} ↓</Link></div></div><div className="hero-visual"><div className="visual-label">NEXNOTE / {theme.toUpperCase()}</div>{theme === 'editorial' ? <div className="editorial-paper"><span>FIELD NOTES / 001</span><h2>Knowledge<br /><em>in context.</em></h2><div className="paper-rule"/><p>Pages become a practice when every reference can lead somewhere useful.</p></div> : theme === 'workbench' ? <Mock kind="editor" text={text} /> : theme === 'graph' ? <Mock kind="graph" text={text} /> : <div className="quiet-specimen"><span>01—04</span><strong>NEX<br />NOTE</strong><i>the quiet system for connected thought</i></div>}</div></section><section id="features" className="section feature-section"><p className="eyebrow">{text.features}</p><div className="feature-grid">{text.facts.map(([title, body], i) => <article key={title}><b>0{i + 1}</b><h3>{title}</h3><p>{body}</p></article>)}</div></section><section id="scenes" className="section scenes"><div className="section-heading"><p className="eyebrow">{text.scenes}</p><h2>{lang === 'zh' ? '不是截图，是可触摸的方向。' : 'Not screenshots. A direction you can touch.'}</h2></div><div className="scene-grid"><Mock kind="editor" text={text} /><Mock kind="graph" text={text} /><Mock kind="chat" text={text} /></div></section><Cta text={text} lang={lang} /><Faq text={text} /></main><Footer text={text} lang={lang} /></Chrome>; }
function App() { const [route, setRoute] = useState(currentRoute); useEffect(() => { const onPop = () => setRoute(currentRoute()); const onClick = (event: MouseEvent) => { const target = (event.target as HTMLElement).closest('a'); if (!target || !target.href || target.origin !== location.origin || target.target === '_blank') return; event.preventDefault(); history.pushState({}, '', target.pathname + target.hash); onPop(); window.scrollTo(0, 0); }; addEventListener('popstate', onPop); document.addEventListener('click', onClick); return () => { removeEventListener('popstate', onPop); document.removeEventListener('click', onClick); }; }, []); const text = copy[route.lang]; useEffect(() => { document.documentElement.lang = route.lang === 'zh' ? 'zh-CN' : 'en'; document.title = route.theme ? `${text.directions[route.theme]} — NexNote` : `NexNote — ${route.lang === 'zh' ? '本地优先的知识' : 'local-first knowledge'}`; }, [route, text]); return route.theme ? <Prototype lang={route.lang} text={text} theme={route.theme} /> : <Gallery lang={route.lang} text={text} />; }

createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
